baseURL: 'https://labbrat.net/'
languageCode: 'en-us'
title: "[Stepan_Kulikov@website ~]# cd ~"
theme: 'PaperMod'
googleAnalytics: 'G-TP3TKT110S'

outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary

params:
  env: production
  ShowBreadCrumbs: true
  ShowReadingTime: true

  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys:
     - "title"
     - "permalink"
     - "summary"
     - "content"

  homeInfoParams:
    Title: "Hi 🤗"
    Content: "My life in one sentence =====> doing tech with questionable efficiency."
  
  socialIcons:
    - name: Github
      url: "https://github.com/Lab-Brat"
    - name: Twitter
      url: "https://twitter.com/Lab__Brat"
    - name: LinkedIn
      url: "https://www.linkedin.com/in/stepan-kulikov-v/"

menu:
  main:
    - identifier: categories
      name: categories
      url: /categories/
      weight: 10
    - identifier: tags
      name: tags
      url: /tags/
      weight: 20
    - identifier: search
      name: "Search"
      pageref: "/search"
      weight: 30
