baseURL: 'https://labbrat.net/'
languageCode: 'en-us'
title: "Stepan Kulikov"
theme: 'PaperMod'
googleAnalytics: 'G-TP3TKT110S'

menu:
  main:
    - identifier: categories
      name: categories
      url: /categories/
      weight: 10
    - identifier: tags
      name: tags
      url: /tags/
      weight: 20
    - identifier: github
      name: GitHub
      url: https://github.com/Lab-Brat
      weight: 30
