baseURL = "https://labbrat.net/"
languageCode = "en-us"
title = "[Stepan_Kulikov@blog]# cd ~"
theme = "PaperMod"
googleAnalytics = "G-TP3TKT110S"

[outputs]
  home = ['html', 'rss', 'json']

[params]
  env = "production"
  ShowBreadCrumbs = true
  ShowReadingTime = true

  [params.fuseOpts]
    isCaseSensitive = false
    shouldSort = true
    location = 0
    distance = 1000
    threshold = 0.4
    minMatchCharLength = 0
    keys = [
      "title",
      "permalink",
      "summary",
      "content",
    ]

  [params.homeInfoParams]
    Title = "Hi 🤗"
    Content = "Welcome to my website!"

  [[params.socialIcons]]
    name = "Github"
    url = "https://github.com/Lab-Brat"

  [[params.socialIcons]]
    name = "Twitter"
    url = "https://twitter.com/Lab__Brat"

  [[params.socialIcons]]
    name = "LinkedIn"
    url = "https://www.linkedin.com/in/stepan-kulikov-v/"

  [params.assets]
    favicon = "/favicons/favicon.ico"
    favicon16x16 = "/favicons/favicon-16x16.png"
    favicon32x32 = "/favicons/favicon-32x32.png"
    apple_touch_icon = "/favicons/apple-touch-icon.png"

[menu]
  [[menu.main]]
    identifier = "categories"
    name = "categories"
    url = "/categories/"
    weight = 10

  [[menu.main]]
    identifier = "tags"
    name = "tags"
    url = "/tags/"
    weight = 20

  [[menu.main]]
    identifier = "about"
    name = "about"
    url = "/about/"
    weight = 30

  [[menu.main]]
    identifier = "search"
    name = "search"
    pageref = "/search"
    weight = 40

