name: hugo
on: [push]
jobs:

  generate:
    name: Generate static content
    runs-on: self-hosted
    steps:

    - name: Pull latest changes
      run: cd /opt/labbrat.net && sudo git pull

    - name: Run Hugo
      run: sudo hugo -s /opt/labbrat.net

    - name: Reload Nginx
      run: sudo docker exec nginx nginx -s reload
