name: hugo
on: [push]
jobs:

  generate:
    name: Generate static content
    runs-on: self-hosted
    steps:
    
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Run Hugo
      run: sudo hugo -s /opt/website/

    - name: Reload Nginx
      run: sudo systemctl reload nginx
