name: hugo
on: [push]
jobs:

  generate:
    name: Generate static content
    runs-on: self-hosted
    steps:
      
    - name: Run Hugo
      run: sudo hugo -s /opt/website/

    - name: Reload Nginx
      run: sudo systemctl reload nginx
